version: "3.3"

services:

  db:
    image: postgres:13.3
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - .:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    container_name: app
    build: .
    command: bash -c "uvicorn app.main:app --host 0.0.0.0 --port 80 --reload"
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db
